// Code generated by goyacc -o ./internal/components/dsl/parser.go ./internal/components/dsl/parser.y. DO NOT EDIT.

//line ./internal/components/dsl/parser.y:2
package dsl

import __yyfmt__ "fmt"

//line ./internal/components/dsl/parser.y:2

const (
	INT = iota
	INT8
	INT16
	INT32
	INT64
	UINT
	UINT8
	UINT16
	UINT32
	UINT64
	BYTE
	RUNE
	FLOAT32
	FLOAT64
	BOOL
	STRING
)

const (
	CREATE = "create"
	READ   = "read"
	UPDATE = "update"
	DELETE = "delete"
	LIST   = "list"
)

type Field struct {
	TokType int
	Name    string
}

type Ent struct {
	Name    string
	Fields  []Field
	Actions []string
}

type AST struct {
	Entities []Ent
}

//line ./internal/components/dsl/parser.y:48
type yySymType struct {
	yys      int
	ast      AST
	entities []Ent
	ent      Ent
	fields   []Field
	field    Field
	val      string
	tokType  int
	actions  []string
}

const IDENT = 57346
const EN_TOK = 57347
const LS_TOK = 57348
const RS_TOK = 57349
const ARROW_TOK = 57350
const COMMA_TOK = 57351
const CREATE_TOK = 57352
const READ_TOK = 57353
const UPDATE_TOK = 57354
const DELETE_TOK = 57355
const LIST_TOK = 57356
const INT_T = 57357
const INT8_T = 57358
const INT16_T = 57359
const INT32_T = 57360
const INT64_T = 57361
const UINT_T = 57362
const UINT8_T = 57363
const UINT16_T = 57364
const UINT32_T = 57365
const UINT64_T = 57366
const BYTE_T = 57367
const RUNE_T = 57368
const FLOAT32_T = 57369
const FLOAT64_T = 57370
const BOOL_T = 57371
const STRING_T = 57372

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"EN_TOK",
	"LS_TOK",
	"RS_TOK",
	"ARROW_TOK",
	"COMMA_TOK",
	"CREATE_TOK",
	"READ_TOK",
	"UPDATE_TOK",
	"DELETE_TOK",
	"LIST_TOK",
	"INT_T",
	"INT8_T",
	"INT16_T",
	"INT32_T",
	"INT64_T",
	"UINT_T",
	"UINT8_T",
	"UINT16_T",
	"UINT32_T",
	"UINT64_T",
	"BYTE_T",
	"RUNE_T",
	"FLOAT32_T",
	"FLOAT64_T",
	"BOOL_T",
	"STRING_T",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 57

var yyAct = [...]int8{
	15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 30, 33, 34, 35, 36,
	37, 38, 10, 39, 31, 11, 8, 5, 12, 11,
	7, 4, 13, 1, 14, 6, 32, 9, 3, 2,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 40,
}

var yyPact = [...]int16{
	22, -1000, -1000, 22, -1000, 26, -1000, 20, 25, 21,
	-1000, -15, 16, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 7, 14, -1000, -1000, -1000, -1000, -1000, -1000, 7,
	-1000,
}

var yyPgo = [...]int8{
	0, 39, 38, 37, 36, 31, 22, 16, 34, 33,
}

var yyR1 = [...]int8{
	0, 9, 1, 2, 2, 5, 3, 3, 6, 4,
	4, 7, 7, 7, 7, 7, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	8, 8,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 2, 7, 1, 2, 2, 1,
	3, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1,
}

var yyChk = [...]int16{
	-1000, -9, -1, -2, -5, 5, -5, 4, 6, -3,
	-6, 4, 7, -6, -8, 15, 16, 17, 18, 19,
	20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
	30, 8, -4, -7, 10, 11, 12, 13, 14, 9,
	-7,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 0, 4, 0, 0, 0,
	6, 0, 0, 7, 8, 16, 17, 18, 19, 20,
	21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
	31, 0, 5, 9, 11, 12, 13, 14, 15, 0,
	10,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:91
		{
			yylex.(*Lex).result = yyDollar[1].ast
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:96
		{
			yyVAL.ast = AST{Entities: yyDollar[1].entities}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:102
		{
			yyVAL.entities = []Ent{yyDollar[1].ent}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./internal/components/dsl/parser.y:106
		{
			yyVAL.entities = append(yyDollar[1].entities, yyDollar[2].ent)
		}
	case 5:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ./internal/components/dsl/parser.y:111
		{
			yyVAL.ent = Ent{
				Name:    yyDollar[2].val,
				Fields:  yyDollar[4].fields,
				Actions: yyDollar[7].actions,
			}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:121
		{
			yyVAL.fields = []Field{yyDollar[1].field}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./internal/components/dsl/parser.y:125
		{
			yyVAL.fields = append(yyDollar[1].fields, yyDollar[2].field)
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./internal/components/dsl/parser.y:130
		{
			yyVAL.field = Field{Name: yyDollar[1].val, TokType: yyDollar[2].tokType}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:136
		{
			yyVAL.actions = []string{yyDollar[1].val}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./internal/components/dsl/parser.y:140
		{
			yyVAL.actions = append(yyDollar[1].actions, yyDollar[3].val)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:146
		{
			yyVAL.val = CREATE
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:150
		{
			yyVAL.val = READ
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:154
		{
			yyVAL.val = UPDATE
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:158
		{
			yyVAL.val = DELETE
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:162
		{
			yyVAL.val = LIST
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:169
		{
			yyVAL.tokType = INT
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:173
		{
			yyVAL.tokType = INT8
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:177
		{
			yyVAL.tokType = INT16
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:181
		{
			yyVAL.tokType = INT32
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:185
		{
			yyVAL.tokType = INT64
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:189
		{
			yyVAL.tokType = UINT
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:193
		{
			yyVAL.tokType = UINT8
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:197
		{
			yyVAL.tokType = UINT16
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:201
		{
			yyVAL.tokType = UINT32
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:205
		{
			yyVAL.tokType = UINT64
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:209
		{
			yyVAL.tokType = BYTE
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:213
		{
			yyVAL.tokType = RUNE
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:217
		{
			yyVAL.tokType = FLOAT32
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:221
		{
			yyVAL.tokType = FLOAT64
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:225
		{
			yyVAL.tokType = BOOL
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./internal/components/dsl/parser.y:229
		{
			yyVAL.tokType = STRING
		}
	}
	goto yystack /* stack new state and value */
}
